apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  selector:
    app: delivery-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
      nodePort: 30000